# Minimal golangci-lint v2 configuration
version: "2"
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - unused
    - staticcheck
    - copyloopvar
formatters:
  enable:
    - gofmt
    - goimports
