# golangci-lint v2.x configuration
version: "2"
run:
  go: '1.23'
  timeout: 5m
  # Limit concurrency to reduce memory usage
  concurrency: 2
settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
linters:
  enable:
    # Core linters with lower resource requirements
    - errcheck
    - govet
    - ineffassign
    - unused
    - staticcheck # Combined linter that includes gosimple in v2
    # Keep copyloopvar as replacement for exportloopref
    - copyloopvar
  # v2 uses enable-only mode by default, no need for disable-all

# Formatters configuration (new in v2)
formatters:
  enable:
    - gofmt
    - goimports
issues:
  # Using standard configurations in v2
  max-issues-per-linter: 0 # Show all issues
  max-same-issues: 0
