repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: local
  hooks:
  - id: golangci-lint-custom
    name: golangci-lint v2
    description: Run golangci-lint v2
    entry: golangci-lint run
    language: system
    types: [go]
    pass_filenames: false
- repo: https://github.com/segmentio/golines
  rev: v0.12.2
  hooks:
  - id: golines
    args: ["--max-len=120", "--base-formatter=goimports"] # Format + Imports + Line Length
- repo: local
  hooks:
  - id: go-mod-tidy
    name: go mod tidy
    entry: go mod tidy
    language: system
    types: [go]
    pass_filenames: false
